[package]
name = "totsuka-bus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
totsuka-core   = { path = "../totsuka-core" }
totsuka-config = { path = "../totsuka-config" }
sqlx           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tokio          = { workspace = true }
chrono         = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
